version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-marchanski
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: haslo123
      MYSQL_DATABASE: Marchanski_Sebastian_k01_spring
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
